data_ingestion:
  raw_data_path: "/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/raw/Crop_recommendation.csv"

data_preprocessing:
  test_size: 0.26
  encoders_path: "/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/models"
  scalers_path: "/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/models"
  model_path: "/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/models"
  processed_data_path: "/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed"

# Random Forest Parameters
random_forest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42